[package]
name = "incdb-query"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
incdb-core = { path = "../incdb-core" }
incdb-storage = { path = "../incdb-storage", optional = true }
thiserror = { workspace = true }
serde = { workspace = true }

[features]
default = []
storage = ["incdb-storage"]

[[example]]
name = "query_example"
path = "../examples/query_example.rs"

