[package]
name = "incdb-api"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
incdb-core = { path = "../incdb-core" }
incdb-storage = { path = "../incdb-storage" }
incdb-query = { path = "../incdb-query" }
thiserror = { workspace = true }
tonic = { workspace = true, optional = true }
tonic-web = { workspace = true, optional = true }
prost = { workspace = true, optional = true }
prost-types = { workspace = true, optional = true }
poem = { workspace = true }
async-graphql = { workspace = true }
async-graphql-poem = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rand = "0.8"

[features]
default = []
grpc = ["tonic", "tonic-web", "prost", "prost-types", "dep:tonic-build"]

[[bin]]
name = "server"
path = "src/bin/server.rs"

[build-dependencies]
tonic-build = { version = "0.11", optional = true }

